import "@/styles/globals.css";

import type { Metadata } from "next";
import { Navbar } from "@/component/common/navbar";
import { Sidebar } from "@/component/common/sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning>
        <Navbar />
        <Sidebar />
        <main className="flex mt-16 ml-64 justify-center">{children}</main>
      </body>
    </html>
  );
}
